/*
 * Copyright (C) 2020 Depwhite Software
 *
 * This file is part of the Depwhite Software project.
 *
 * Depwhite Software project can not be copied and/or distributed without the express
 */

const CUSTOMER_TYPE = {
  SHOP: "SHOP",
  DESIGNER: "DESIGNER",
  PROJECT_OWNER: "PROJECT_OWNER",
  HOUSE_OWNER: "HOUSE_OWNER",
  CONSTRUCTOR: "CONSTRUCTOR",
}
const CUSTOMER_CONTACT_TYPE = {
  PERSONAL: "PERSONAL",
  CORPORATION: "CORPORATION",
}

const CONTACT_TYPE = {
  SERVICE: "SERVICE",
  ESTATE: "ESTATE",
  CONTRACTOR: "CONTRACTOR",
  DESIGN: "DESIGN",
  AFFILIATED: "AFFILIATED",
  BOUGHT_SOLD: "BOUGHT_SOLD",
  ANOTHER: "ANOTHER",
}
const CUSTOMER_STATUS = {
  GREEN: "GREEN",
  YELLOW: "YELLOW",
  RED: "RED",
}

const SHOP_TYPE = {
  MATERIAL: "MATERIAL",
}

const RELIGION = {
  CHRISTIANITY: "CHRISTIANITY",
  ISLAM: "ISLAM",
  BUDDHISM: "BUDDHISM",
  BRAHMANISM_HINDUISM: "BRAHMANISM_HINDUISM",
  AGNOSTIC_ATHEIST: "AGNOSTIC_ATHEIST",
}

const CUSTOMER_ACTIVE = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DELETED: "DELETED",
}

const COMPANY_CONTACT = {
  PROJECT_OWNER: "PROJECT_OWNER",
  HOME_BUILDER: "HOME_BUILDER",
  COORDINATE: "COORDINATE",
  PM: "PM",
  DESIGNER: "DESIGNER",
  ARCHITECT: "ARCHITECT",
  ENGINEER: "ENGINEER",
  CONTRACTOR: "CONTRACTOR",
  TECHNICIAN: "TECHNICIAN",
  SALES_OFFICE: "SALES_OFFICE",
  PURCHASE: "PURCHASE",
  ANOTHER: "ANOTHER",
}

const ADDRESS_TYPE = {
  PRIMARY: "PRIMARY",
  SECONDARY: "SECONDARY",
}

export { CUSTOMER_TYPE, CUSTOMER_STATUS, CONTACT_TYPE, SHOP_TYPE, RELIGION, CUSTOMER_ACTIVE, ADDRESS_TYPE, CUSTOMER_CONTACT_TYPE }
