interface CustomerType {
  readonly customer_id: number
  readonly customer_code: string
  readonly customer_type: string
  readonly firstname: string
  readonly lastname: string
  readonly id_card: string
  readonly line: string
  readonly email: string
  readonly contact_type: string
  readonly shop_type: string
  readonly customer_status: string
  readonly phone: string
  readonly religion: string
  readonly career: string
  readonly salary: number
  readonly address: string
  readonly province_id: number
  readonly district_id: number
  readonly sub_district_id: number
  readonly zip_code: string
  readonly isactive: boolean
  readonly createby: string
  readonly createdatetime: string
  readonly updateby: string
  readonly updatedatetime: string
  readonly shop_name: string
  readonly crm_details_id: number
  readonly name: string
  readonly birthday: string
  readonly contract_other: string
  readonly birthday_other: string
  readonly number_of_children: number
  readonly like_activity: string
  readonly dislike_activity: string
  readonly contact_detail_id: number
  readonly type: string
  readonly position: string
  readonly business_detail_id: number
  readonly tax_number: string
  readonly branch_number: string
  readonly certificate: string
  readonly document_vat_20: string
  readonly history: string
  readonly business_type: string
  readonly name_of_director: string
  readonly number_of_employee: number
  readonly income: number
  readonly project_characteristics: string
  readonly interior_area: string
  readonly outside_area: string
  readonly number_of_transport: string
  readonly transport_type: string
  readonly pos_system: string
  readonly work_explain: string
  readonly best_selling_product: string
}
export { CustomerType }
